name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '^1.21', 'oldstable', 'stable' ]
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Install golangci-lint
      uses: golangci/golangci-lint-action@v6
      with:
        install-mode: "goinstall"

    - uses: taiki-e/install-action@just

    - name: Build
      run: |
        just
      env:
        GOPATH: /home/runner/work/go

