name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: stable
    - uses: golangci/golangci-lint-action@v6
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '^1.21', 'oldstable', 'stable' ]
    steps:
    - uses: extractions/setup-just@v1  
    - uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go }}
    - uses: actions/checkout@v4
    - name: Build
      run: just build test